paths:
  base_dir: "."
  recordings_dir: "recordings"
  outputs_dir: "outputs"
  models_dir: "models"
  logs_dir: "logs"
  tmp_dir: "tmp"

audio:
  sample_rate: 16000
  channels: 1

whisper:
  model: "medium.en"
  diarize: true

